name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '7 7 */7 * *'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          repository: 'Matthias-Wandel/jhead'

      - name: Check for new version
        run: |
          $lastBuild = try { curl https://api.github.com/repos/ltguillaume/jhead-win64/releases/latest | ConvertFrom-Json | Select -exp tag_name } catch { echo 0 }
          $latestTag = git rev-parse --short HEAD
          $latestVer = Select-String -Path .\jhead.c -Pattern 'JHEAD_VERSION \"(.*?)\"'
          $latestVer = $latestVer.Matches.Groups[1].Value +"-"+ $latestTag
          if ($latestVer -eq $lastBuild) {
            echo "No new version"
          } else {
            echo "New version: $latestVer"
            "TAG=$latestTag" | Out-File -FilePath $env:GITHUB_ENV -Append
            "VER=$latestVer" | Out-File -FilePath $env:GITHUB_ENV -Append
          }

      - name: Set up Developer Command Prompt
        if: ${{ env.VER != '' }}
        uses: ilammy/msvc-dev-cmd@v1
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

      - name: Build executable
        if: ${{ env.VER != '' }}
        run: .\make.bat

      - name: Create release
        if: ${{ env.VER != '' }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: '${{ env.VER }}'
          name: 'JHEAD for Windows (${{ env.VER }})'
          body: 'Created from https://github.com/Matthias-Wandel/jhead/tree/${{ env.TAG }}'
          files: jhead.exe
